export const SNACKBAR_SUCCESS = "SNACKBAR_SUCCESS";
export const SNACKBAR_ERROR = "SNACKBAR_ERROR";
export const SNACKBAR_INFO = "SNACKBAR_INFO";
export const SNACKBAR_CLEAR = "SNACKBAR_CLEAR";

export const PROGRESSBAR_SHOW = "PROGRESSBAR_SHOW";
export const PROGRESSBAR_CLEAR = "PROGRESSBAR_CLEAR";